### ISSUE TITLE
Bug in Network.input

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#40]
The setting of network_names to NULL in the script Network.input (line 41) breaks the batch scripts. The Network.input script sets the network names based on `if (inc_improve=="y")`  type conditionals. These types of conditionals don't get set in the batch mode of the scripts and so initializing these vectors to NULL breaks the batch scripts because they never get set back to actual network names after the Network.input script is sourced. The offending "source" command that unsets these variables happens at line 1174 of R_analysis_code/AQ_Misc_Functions.R.

Suggested fix is to wrap these lines in Network.input in a conditional to ignore them if the scripts are in batch mode:
```
if ( batch != 'y' ){
network_names <- NULL
network_label <- NULL
}
```

**Comment by wkappel** [comment]
Thanks for looking at this Zac. I'm thinking that maybe the easier solution is to just remove the sourcing of the Network.input file from the end of the AMET_batch.input file. I added that in there at the last minute because of some error that I thought I was getting from not sourcing that file, but I don't think that should be the case. That file should not need to be sourced with the batch scripts. If you get a chance, could you try removing the sourcing of the Network.input file from the end of the AMET_batch.input file and see if the code still breaks. If it does, I'll need to dig deeper, or simply implement the change you suggest. Thanks.

**Comment by zacadelman** [comment]
This "fix" that I proposed breaks the non-batch scripts because they never use the batch command.  I'll take a look at what you propose and report back.

**Comment by zacadelman** [comment]
Wyat, it looks like your suggested fix works. Commenting out the source command at the end of the AMET_batch.input worked for me.

**Comment by wkappel** [comment]
Good to hear. Thanks for catching this issue. Closing this issue out.
