### ISSUE TITLE
Enhancement Request: Species <-> Networks and Error Handling

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#41]
AMET result in a nebulous error when you try to plot a species from a network that doesn't include said species.  The error may look something like this:

```
Error in `$<-.data.frame`(`*tmp*`, "good_ob", value = 0) :
  replacement has 1 row, data has 0
Calls: Average -> $<- -> $<-.data.frame
Execution halted
```

The system would be much more user friendly if (1) there was a sanity check on the species (AMET_AQSPECIES) and network (e.g. AMET_CSN) pairs; and (2) a table (maybe a new Appendix in the UG) that shows what species are available for each network. When the check is written for (1), there would be an informative error that says something like "AMET_AQSPECIES O3_8hrmax is not available in the network AMET_CSN; please refer to Table XXX in the AMET user's guide to see the list of species available for each network in the AMET database."

**Comment by wkappel** [comment]
I'd hate to hard code a list of available species for each network into the AMET code since network species availability does change from time to time. I could put a check in that if a query for a species returns all null values that AMET reports a message like "No data found for [species] from [network] network. It may be that [network] does not observe [species] or no data are available for your query specifications." Now, there are obviously other reasons why there may be no data for a particular query, but at least this would report that no data were found and let the user figure out why. There is a list of species per network in the User's Guide. I could refer users to that guide as well.

What do you think?

**Comment by wkappel** [comment]
To this end, I've updated the scripts that handle multiple networks to avoid crashing if a network returns an empty query. Previously the scripts would crash if any query returned no results. Now, the script will attempt to continue on to the next network if an empty result is returned. This should make a number of the scripts more robust. If all the queries return no results, the script still crashes however.
