### ISSUE TITLE
Login/Pass

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#8]
New unified met/aq scripts use a single database script to create projects (if needed) and load data. There is a way to include your login and password as variables in the script, otherwise, if these variables aren't set the database load script asks for your login info upon execution.  

should we include login and password env vars as examples/optional in the script (e.x., aqProject.csh) to bypass the interactive mode?

how do these variables connect to the amet-config.R scripts? Is there a way to reference that centralized configuration script from these database loading scripts?

**Comment by wkappel** [comment]
We'll need to discuss this further at our next meeting. There are several way we could approach this. I don't particularly like putting the login/pass info as environment variables in the run script, as people share run scripts all the time. We could create the option to have essentially two AMET login/pass combos, one that is a more powerful user that can create and modify the database and another that just has read access. The user could then opt to include one or both of those combos in the config file, and the script can just check to see if the more powerful user info is in that file. If so, use that. If not, prompt the user for it.

Thanks how I'm envisioning it anyway.

**Comment by wkappel** [comment]
Looking at this further, I decided to put the option to specify the login/password in the script via a set command (not setenv). I feel this is pretty secure because a user could prevent other users from reading the script via file permission settings. 

As the script is setup now, it will first check to see if the login/password are set via the script, if not it will prompt the user for the login/password. A user can still submit the script to the queue, specifying the login/pass either via the script or the qsub command line. I think this option will work well overall as it allows the user to dictate the level of password control they want to have. 

For now I'm leaving the analysis scripts to get the login/password via the config file, as AMET has always been.

**Comment by zacadelman** [comment]
The database load scripts have redundancy that we should eliminate.  For example AQ_matching.R:

```
amet_base        <- Sys.getenv('AMETBASE')
base.command     <- paste(amet_base,"/configure/amet-config.R",sep="")

source(base.command)

args              <- commandArgs(2)
amet_login        <- args[1]
amet_pass         <- args[2]
```
It sources the config file, and in doing so gets the amet_login and amet_pass settings.  It also passes these variables in via the csh script arguments. 

My opinion is that we should just leave these scripts they way they have been, which is to use the settings from the central configuration script and not deal with any of the password stuff in either the database load or analysis scripts. I'm afraid we're over engineering this.

**Comment by wkappel** [comment]
That script gets more than just the login/pass from the amet-config.R file. It also gets the paths to the site compare executables. So, I'm sourcing it for those paths and not the login/pass info.

I understand your concern over the credentials. Maybe by default we have it setup to just read the credentials from the config file, otherwise the user can enter the info manually. That would not be difficult to do.

**Comment by wkappel** [comment]
So, I updated the aqProject.csh script to allow the user to specify mysql_login and mysql_pass variables that can either be the actual mysql login and password credentials, or they can specify them as "config_file", in which case they will be read from the amet-config.R file. If they comment out those variables altogether, the script will prompt them for the login/pass or read them from the qsub command line if they submit to the queue.

I think this covers all the basis. By default I have the script values set to "config_file" so they are being read from the amet-config.R file. The analysis scripts still just read the login/pass from the config file only, but it would be easy to create the same setup for those. But I don't know that that's necessary right now.

The scripts in the dbSetup directory still prompt the user for the login/pass as the only option, but I think this makes sense given that those scripts either create a new MySQL user or delete an existing database.
